services:
  digger:
    build:
      context: ../src/Digger
      dockerfile: ../../infra/digger/Dockerfile
    container_name: digger
    restart: unless-stopped
    environment:
      Logging__Level__Default: Warning
      Logging__Level__Microsoft: Warning
      Logging__LogLevel__Microsoft_Hosting_Lifetime: Warning
      Logging__LogLevel__Microsoft__EntityFrameworkCore__Database__Command: Warning
    depends_on:
      - transmission
    volumes:
      - ${TRANSMISSION_DOWNLOADS_DIR}/movies:/downloads/movies:rw
      - ${DIGGER_DATA_DIR}:/digger/data
    networks:
      default:
        ipv4_address: 10.51.0.2
  frigate:
    user: 0:0
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${FRIGATE_CONFIG_DIR}:/config
      - ${FRIGATE_MEDIA_DIR}:/media/frigate
    ports:
      - 8971:8971
      - 8554:8554
      - 8555:8555/tcp
      - 8555:8555/udp
      - 5000:5000
    networks:
      default:
        ipv4_address: 10.51.0.3
    environment:
      FRIGATE_RTSP_PASSWORD: ${FRIGATE_PASSWORD}
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ${HOMEASSISTANT_CONFIG_DIR}:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 10.51.0.4
    ports:
      - 8123:8123
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    restart: unless-stopped
    user: 0:0
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ${JELLYFIN_CONFIG_DIR}:/config
      - ${JELLYFIN_CACHE_DIR}:/cache
      - ${JELLYFIN_MEDIA_DIR}:/media
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_SERVER_URL}
    networks:
      default:
        ipv4_address: 10.51.0.5
  mosquitto:
    image: eclipse-mosquitto:openssl
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ${MOSQUITTO_DATA_DIR}:/mosquitto/data
      - ${MOSQUITTO_CONFIG_DIR}:/mosquitto/config
      - ${MOSQUITTO_LOGS_DIR}:/mosquitto/log
    networks:
      default:
        ipv4_address: 10.51.0.6
    ports:
      - 1883:1883
  n8n:
    image: docker.n8n.io/n8nio/n8n:next
    container_name: n8n
    restart: unless-stopped
    user: "0:0"
    environment:
      GENERIC_TIMEZONE: "Europe/Lisbon"
      TZ: "Europe/Lisbon"
      N8N_HOST: automation.mouras.me
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      N8N_PROTOCOL: https
      N8N_EDITOR_BASE_URL: https://automation.mouras.me/
      WEBHOOK_URL: https://automation.mouras.me/
      DB_TYPE: "postgresdb"
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_SCHEMA: public
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${N8N_DATA_DIR}:/home/node/.n8n
    networks:
      default:
        ipv4_address: 10.51.0.7
  npm:
    container_name: npm
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    environment:
      TZ: Europe/Lisbon
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ${NPM_DATA_DIR}:/data
      - ${NPM_CERTIFICATE_DIR}:/etc/letsencrypt
    networks:
      default:
        ipv4_address: 10.51.0.8
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    networks:
      default:
        ipv4_address: 10.51.0.9
    restart: unless-stopped
    volumes:
      - ${OLLAMA_DIR}:/root/.ollama
  opeclaw:
    build:
      context: ./openclaw
      dockerfile: Dockerfile
    container_name: openclaw
    restart: unless-stopped
    ports:
      - 18789:18789
    networks:
      default:
        ipv4_address: 10.51.0.10
  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: openwebui
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 10.51.0.11
    ports:
      - 8080:8080
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
    volumes:
      - ${OPEN_WEBUI_DATA_DIR}:/app/backend/data
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    container_name: pgadmin
    user: "0:0"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      default:
        ipv4_address: 10.51.0.12
    volumes:
      - ${PGADMIN_DATA_DIR}/servers.json:/pgadmin4/servers.json
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PORTAINER_DATA_DIR}:/data
    networks:
      default:
        ipv4_address: 10.51.0.13
    environment:
      - PORTAINER_MANAGE_EXTERNAL_STACKS=1
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:15
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      default:
        ipv4_address: 10.51.0.14
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 10.51.0.15
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - USER=${TRANSMISSION_USERNAME}
      - PASS=${TRANSMISSION_PASSWORD}
      - WHITELIST=${TRANSMISSION_WHITELIST}
      - HOST_WHITELIST=${TRANSMISSION_WHITELIST}
    volumes:
      - ${TRANSMISSION_CONFIG_DIR}:/config
      - ${TRANSMISSION_DOWNLOADS_DIR}:/downloads:rw
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.51.0.0/24