FROM ubuntu:latest

EXPOSE 9091 51413 51413/udp

ENV TRANSMISSION_USER="transmission" 
ENV TRANSMISSION_PASSWORD="transmission" 
ENV TRANSMISSION_ALLOWED="*"

COPY scripts/transmission.entrypoint.sh /transmission.entrypoint.sh
ENTRYPOINT [ "sh", "/transmission.entrypoint.sh" ]
