FROM python:3.12-slim

EXPOSE 8000

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=1
ENV UV_LINK_MODE=copy
ENV PATH="/root/.local/bin:$PATH"
ENV HOST="0.0.0.0"
ENV PORT="8000"
ENV AUTH_USE_AUTH="false"
ENV OPENAI_API_BASE_URL=""
ENV OPENAI_BASE_URL=""

COPY scripts/externals/honcho.entrypoint.sh honcho.entrypoint.sh

ENTRYPOINT ["sh", "honcho.entrypoint.sh"]
