FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=1
ENV UV_LINK_MODE=copy
ENV PATH="/root/.local/bin:$PATH"
ENV HOST="0.0.0.0"
ENV PORT="8000"
ENV AUTH_USE_AUTH="false"
ENV OPENAI_API_BASE_URL=""
ENV OPENAI_BASE_URL=""

RUN set -eu
RUN apt-get update -yq
RUN apt-get install -yq --no-install-recommends build-essential curl git libpq-dev postgresql-client
RUN pip install --no-cache-dir uv
RUN git clone https://github.com/plastic-labs/honcho.git .
RUN uv sync

EXPOSE 8000

COPY scripts/externals/honcho.entrypoint.sh honcho.entrypoint.sh

RUN chmod +x honcho.entrypoint.sh

ENTRYPOINT ["sh", "honcho.entrypoint.sh"]
