FROM ubuntu:latest

ENV PATH="/root/.local/bin:$PATH"

EXPOSE 1234

RUN apt update -qy

RUN apt install wget -qy

RUN wget https://lmstudio.ai/install.sh

RUN sh install.sh

RUN rm install.sh

RUN lms get $LLM_MODEL

RUN lms load $LLM_MODEL

ENTRYPOINT [ "lms", "server", "start" ]