name: tools-services
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/tools/portainer:/data
    networks:
      shared:
    environment:
      - PORTAINER_MANAGE_EXTERNAL_STACKS=1
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      shared:
    volumes:
      - ~/tools/pgadmin/servers.json:/pgadmin4/servers.json