FROM ubuntu:latest

WORKDIR /lms

ENV PATH="/root/.local/bin:$PATH"

ENV LLM_MODEL="qwen/qwen3.5-4b"

EXPOSE 4321

COPY scripts/image.entrypoint.lmstudio.sh lmstudio.entrypoint.sh

RUN chmod +x lmstudio.entrypoint.sh

ENTRYPOINT [ "sh", "lmstudio.entrypoint.sh" ]