FROM ubuntu:latest

WORKDIR /lms

ENV PATH="/root/.local/bin:$PATH"

ENV LLM_MODEL="qwen/qwen3.5-4b"

ENV EMBEDDING_MODEL="text-embedding-nomic-embed-text-v1.5"

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        libatomic1 \
        libgomp1 \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 4321

COPY scripts/image.entrypoint.lmstudio.sh lmstudio.entrypoint.sh

RUN chmod +x lmstudio.entrypoint.sh

ENTRYPOINT [ "sh", "lmstudio.entrypoint.sh" ]
