name: Deployment Workflow
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Test the build only?"
        required: true
        type: boolean
        default: true
      host:
        description: "Select the host to deploy to:"
        required: true
        type: choice
        options:
          - rpi
          - beelink
      environment:
        description: "Select the environment to deploy to:"
        required: true
        type: choice
        options:
          - mouras-home-lab
        default: mouras-home-lab
      bring_down_first:
        description: "Bring down infrastructure down."
        required: true
        type: boolean
        default: false
      update_images:
        description: "Update Docker images before deployment."
        required: true
        type: boolean
        default: false
jobs:
  deploy:
    name: "Deploy to: ${{ inputs.environment || 'mouras-home-lab' }}"
    runs-on: ${{ inputs.host }}
    environment: ${{ inputs.environment || 'mouras-home-lab' }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
      - name: Redacting configurations
        env:
          TRANSMISSION_USERNAME: ${{ vars.TRANSMISSION_USERNAME }}
          TRANSMISSION_PASSWORD: ${{ secrets.TRANSMISSION_PASSWORD }}
        run: bash .github/workflows/scripts/redact-digger-config.sh
      - name: Create .env file from selected environment
        env:
          ENVIRONMENT_VARS: ${{ toJson(vars) }}
          ENVIRONMENT_SECRETS: ${{ toJson(secrets) }}
        run: bash .github/workflows/scripts/create-environment-file.sh
      - name: Bring current infrastructure down
        if: ${{ inputs.bring_down_first == true }}
        run: docker compose -f infra/compose.yaml down --remove-orphans
      - name: Pull new images
        if: ${{ inputs.bring_down_first == true && inputs.update_images == true }}
        run: docker compose -f infra/compose.yaml pull
      - name: Build stack
        run: docker compose -f infra/compose.yaml build
      - name: Deploy stack
        if: ${{ inputs.dry_run == false }}
        run: docker compose -f infra/compose.yaml up -d
      - name: Clean docker dangling images
        run: bash .github/workflows/scripts/clean-docker.sh