name: Home Lab Deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to:'
        required: true
        type: choice
        default: 'mouras-home-lab'
        options:
          - mouras-home-lab
jobs:
  deploy:
    name: Home lab deployment
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:

      # Check out the repository to access the .env file and deployment scripts
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Set up Docker on the runner to enable building and deploying the Docker Compose application
      - name: Set up docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          rm get-docker.sh

      # Create .env file from the variables and secrets attached to the selected GitHub Environment
      - name: Create .env file from selected environment
        env:
          ENVIRONMENT_VARS: ${{ toJson(vars) }}
          ENVIRONMENT_SECRETS: ${{ toJson(secrets) }}
        run: |
          jq -r 'to_entries[] | select(.key != "GITHUB_TOKEN") | "\(.key)=\(.value | tostring)"' <<< "$ENVIRONMENT_VARS" > infra/.env
          jq -r 'to_entries[] | select(.key != "GITHUB_TOKEN") | "\(.key)=\(.value | tostring)"' <<< "$ENVIRONMENT_SECRETS" >> infra/.env
          cat infra/.env

      # Deploy the application using Docker Compose, running the containers in detached mode
      - name: Run compose file
        run: docker compose -f infra/compose.yaml up -d --quiet-pull